config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :transactions,only: [:index, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord

  def credit?
    ['1' , '4' , '5' , '6' , '7' , '8'].include? category
  end

  def self.sum_transactions(transactions)
    transactions.reduce(0) { |acc, transaction| transaction.credit? ? acc += transaction.value : acc -= transaction.value }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  def index
    @transactions = Transaction.all
  end
  
  def new
    @transaction = Transaction.new
  end

  def create
    begin
      parse_transactions
      redirect_to transactions_path
    rescue => exception      
      @transaction = Transaction.new   
      flash.now[:error] = "Arquivo não está de acordo com os parametros .txt"
      render :new
    end 
  end


  private

  def transaction_params
    params.require(:transaction).permit(:cnab_file)  
  end

  def parse_transactions
    File.open(transaction_params[:cnab_file]).each do |line|
      Transaction.create!(
        category: line[0].to_i,
        occurence: "#{line[1..4]}/#{line[5..6]}/#{line[7..8]}".to_date,
        hour: "#{line[42..43]}:#{line[44..45]}:#{line[46..47]}",
        value: line[9..18].to_f / 100.0,
        cpf: line[19..29],
        card_number: line[30..41],
        store_name: line[62..80].strip,
        store_owner: line[48..61].strip        
      )
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParsingTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class='container mt-5'>
  <h1>Olá!</h1>
  <p>Faça login para realizar o parse de seu arquivo .txt</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Transactions", new_transaction_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="container-index-center">
  <div>
    <div class="mt-4">
      <h1>Movimentações </h1>
    </div>
    <p class='border-bottom'><strong>Total:</strong> <%= Transaction.sum_transactions(@transactions) %></p>
    <br>
    <div class="row">
      <% @transactions.each do |line| %>
          <div class="col-6">
            <div class ="card-right">
              <h1 class="border-bottom border-top"><%= line.store_owner %></h1>
              <p><strong>Occurence:</strong> <%= line.occurence %></p>
              <p><strong>Card:</strong> <%= line.card_number %></p>
              <p><strong>Store_name:</strong> <%= line.card_number %></p>
              <p><strong>Card:</strong> <%= line.card_number %></p>
              <p class='border-bottom'><strong>Value:</strong> <%= line.value %></p>
            </div>
          </div>
    <% end %>
    </div>
    <br>
  </div>
</div>

app/views/transactions/new.html.erb
<div class='container mt-5'>
  <h2> Novas Analises de transações </h2>

  <%= simple_form_for(@transaction) do |f| %>
    <%= f.input :cnab_file, label: "Faça o upload do seu arquivo .txt", as: :file %>
    <%= f.button :submit, "Criar", class:'btn btn-success' %>
  <% end %>
</div>